// <auto-generated />
namespace ContactAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_birthday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_birthday));
        
        string IMigrationMetadata.Id
        {
            get { return "201812050642396_Add_birthday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
